name: Update Dependency Graph for Gradle
on:
  push:
    branches:
      - main
      - Gradle-dependency-graph-fdf30faccca482ce
  workflow_dispatch: 
jobs:
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        id: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Java
        id: setup
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: temurin
          java-version: 17
      - name: Submit dependencies
        id: submit
        uses: gradle/actions/dependency-submission@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0
      - name: Log snapshot for user validation
        id: validate
        run: cat
          /home/runner/work/snyk-test-toolargetool/snyk-test-toolargetool/dependency-graph-reports/update_dependency_graph_for_kotlin-dependency-graph.json
          | jq
    permissions:
      contents: write
